version: '3.8'
services:
  backend:
    build: backend/
    container_name: dreamlabs-backend
    command: npm run start:dev
    volumes:
      - .:/backend/app
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - DB_USER=postgres
      - DB_PASS=dbpassword
      - DB_HOST=postgres
      - DB_NAME=accounting
  postgres:
    container_name: dreamlabs-database
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_DB: accounting
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
