apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounting-db-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounting-db
  template:
    metadata:
      labels:
        app: accounting-db
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PASS
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_NAME
          ports:
            - containerPort: 5432
